### ISSUE TITLE
PROJECT WORKFLOW 🧑‍💻

### ISSUE THREAD

**Issue by Aryamanz29** [Aryamanz29/Elastic-CFC#1]
**Getting Started**  :point_down:
- **Java SE Dev Kit Download here:** https://www.oracle.com/java/technologies/javase-jdk16-downloads.html 
- **Elastic Search Download**: https://www.elastic.co/downloads/elasticsearch
- **Configuration**: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-18-04
- **Django Elasticsearch DSL is a package that allows indexing of Django models in elastic search** : https://github.com/django-es/django-elasticsearch-dsl

**Comment by codesankalp** [comment]
Done :+1:

**Comment by codesankalp** [comment]
Closing this issue.
Thanks, @Aryamanz29 and @Sai-02
