### ISSUE TITLE
Dockerize this project

### ISSUE THREAD

**Issue by Aryamanz29** [Aryamanz29/Elastic-CFC#22]
- `Dockerize` this project
- Update `README.md` as per change

**Comment by harikishantk** [comment]
Interested, may I know level and the points for this?

**Comment by Aryamanz29** [comment]
> Interested, may I know level and the points for this?

lv3

**Comment by harikishantk** [comment]
I'm SWOC Participant, does this issue comes under `SWOC` label? If yes, I could start right away. :sweat_smile:

**Comment by Aryamanz29** [comment]
> I'm SWOC Participant, does this issue comes under `SWOC` label? If yes, I could start right away. sweat_smile

Yes this project comes under both SWOC'21 and DWOC'21 , You can start working on this :smile:

**Comment by hazemessam** [comment]
Can I work on it under GSSoC'22

**Comment by Aryamanz29** [comment]
@hazemessam  Sure go ahead :+1:

**Comment by hazemessam** [comment]
@Aryamanz29, please, can you check my PR
https://github.com/Aryamanz29/Elastic-CFC/pull/25
